[instance]
chain_id = 6
epoch_duration_secs = 7200
recurring_lockup_duration_secs = 14400
voting_duration_secs = 7200
is_testnet = true
genesis_timestamp_microseconds = 1726574400000000

[mempool]
max_batch_delay_ms = 500
max_batch_size_bytes = 5000000
sync_retry_delay_ms = 2000
sync_retry_nodes = 3

[moonshot]
block_recency_bound_ms = 500
halt_block_production_when_no_txs = false
leader_elector = "FairSuccession"
max_block_delay_ms = 2500
max_payload_items_per_block = 50
message_recency_bound_rounds = 20
sync_retry_delay_ms = 1000
timeout_delay_ms = 5000

[node]
connection_refresh_timeout_sec = 1
resume = true
root_ca_cert_path = "ca_certificate.pem"
rpc_access_port = 26000
server_cert_path = "server_supra_certificate.pem"
server_private_key_path = "server_supra_key.pem"

[node.database_setup.dbs.chain_store.rocks_db]
path = "smr_storage"
enable_pruning = true

[node.database_setup.dbs.ledger.rocks_db]
path = "ledger_storage"

[node.database_setup.prune_config]
epochs_to_retain = 84